### ISSUE TITLE
add me back

### ISSUE THREAD

**Issue by genocydr** [EmK530/BloxDump#11]
Emk, ever since dan nuked rffc i havent been able to get in contact with you!! you were a cool guy and i could actually discuss things with you, please add me back.

**Comment by genocydr** [comment]
sorry for the off topicness

**Comment by EmK530** [comment]
you can contact me on Discord my user is emk530

**Comment by genocydr** [comment]
![image](https://github.com/user-attachments/assets/380c8fc0-167c-4acb-b9f2-b968bbe51434)
sent
