### ISSUE TITLE
[QUESTION] is there any way to match the dumped files with their respective files in the cache?

### ISSUE THREAD

**Issue by catb0x** [EmK530/BloxDump#12]
title, i have tried searching for the file names (without the file type part) and i couldnt find them in %temp%\Roblox\http

**Comment by EmK530** [comment]
The cache file names differ from the links contained within that BloxDump downloads from, which also has a hash that I think is what makes it into the final filename.

**Comment by catb0x** [comment]
if im understanding u correctly, what hash function would the file names be in? or is there another way i can match the dumped files with their cached files?

**Comment by catb0x** [comment]
if im understanding u correctly, what hash function would the file names be in? or is there another way i can match the dumped files with their cached files?

**Comment by catb0x** [comment]
nvm figured this out ^_^
