### ISSUE TITLE
[SUGGESTION]: organizing of each dumped asset in a folder with correct names of such.

### ISSUE THREAD

**Issue by Vich2094** [EmK530/BloxDump#4]
something like this,
sorry i tried to not make this confusing as possible.

![image](https://github.com/EmK530/BloxDump/assets/55785917/b9185610-773c-4aac-ae86-1dea791a406c)

**Comment by EmK530** [comment]
is this a suggestion of renaming the folders produced? not really understanding this one

**Comment by Vich2094** [comment]
Basically when, i dump an asset, the asset hash name gets very confusing for me, i want it to understand which asset name it is. 
if its not possible you dont need to do it.

**Comment by Vich2094** [comment]
Its an example, of what i want to do with this.

> something like this, sorry i tried to not make this confusing as possible.
> 
> ![image](https://private-user-images.githubusercontent.com/55785917/300203164-b9185610-773c-4aac-ae86-1dea791a406c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjU4MTYsIm5iZiI6MTcwNjQyNTUxNiwicGF0aCI6Ii81NTc4NTkxNy8zMDAyMDMxNjQtYjkxODU2MTAtNzczYy00YWFjLWFlODYtMWRlYTc5MWE0MDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA3MDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YmNmYWY4NDM5ZDZkZDY4ZGNlZDcyNjE2NjYxMzg4ZGI3ODI4YTE5NDY2YmIyY2ViNmMwM2I2MGM1NjczOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zOO9TZTlMniwI9UP2n-NZWx9wzZAGhl1fHNTjklAL6k)

**Comment by EmK530** [comment]
oh if you mean fixing asset names to not be random hashes then sadly it's not something I've figured out yet because the files I check don't contain an asset ID or name
