### ISSUE TITLE
[SUGGESTION]: Option to set the Drive you want to scan for assets

### ISSUE THREAD

**Issue by Win-DVD** [EmK530/BloxDump#5]
I have an old 10 install with Roblox on a separate drive, And it would be very nice to be able to select that drive and extract the assets from that instead of just the C: drive.

**Comment by EmK530** [comment]
Yeah an attempt count is probably smart, possible reason it didn't exist was because getting forbidden by a CDN link is very unexpected
As for the separate drive dumping I'll see if that is possible

**Comment by Win-DVD** [comment]
> Yeah an attempt count is probably smart, possible reason it didn't exist was because getting forbidden by a CDN link is very unexpected
> As for the separate drive dumping I'll see if that is possible

I forked it and made a quick bandaid to fix the download issue, The reason I was getting forbidden downloads is because I was extracting a cache made in 2022

**Comment by EmK530** [comment]
Alright, if it's a change worth implementing feel free to make a pull request!
