### ISSUE TITLE
Saving the model's position as in the game

### ISSUE THREAD

**Issue by MrKinoba** [EmK530/BloxDump#8]
Hello. Is it possible to make the meshes stay in place like in the game? Or download the entire map as it is? Due to the fact that the models are divided into many parts, it is not clear which model they belong to. I hope I explained it clearly, I use Google Translate.

**Comment by EmK530** [comment]
Hi, BloxDump isn't able to see information like positions. What gets downloaded is whatever the Roblox Client uses.
Positions are not applied to the mesh but instead to the actual object using the mesh.
