### ISSUE TITLE
No download

### ISSUE THREAD

**Issue by jojocraftde-dev** [EmK530/BloxDump#9]
I extracted everything as said, and im in a roblox world but it just says
```
INFO BloxDump started. 
                                                                                                 
INFO Ripping loop completed. 
```
![](https://i.ibb.co/xzZcvpQ/image-2024-09-26-164419772.png)

**Comment by EmK530** [comment]
Do you play on the client from the website or from Microsoft Store?

**Comment by jojocraftde-dev** [comment]
> Do you play on the client from the website or from Microsoft Store?

Im using the Microsoft version

**Comment by EmK530** [comment]
The Microsoft Store version might be storing cache differently/in another location. I'll respond back when I've investigated if this is possible to fix or no.

**Comment by EmK530** [comment]
Sorry, I can't seem to find where Roblox's UWP app saves cached assets, or if it's even saved at all. If it's ever discovered I'll update to support it.
For now you'll have to use the Roblox version you get from their website.

**Comment by EmK530** [comment]
Hi, I'm closing this as completed because I located where Roblox stores their cache for the Microsoft Store version. It will be supported in v5.1.0 which releases soon.
